### ISSUE TITLE
Implement Settings

### ISSUE THREAD

**Issue by licaon-kter** [icasdri/Mather#1]
It's a placeholder now or?

F-Droid, 6.0.1

**Comment by icasdri** [comment]
It's a placeholder for now. Not implemented as of yet. Thanks for the notice though.

**Comment by icasdri** [comment]
Some settings that would be nice to have. 
- Customization of the user keys keyboard (allow users to set what buttons show up on the 4x6 keyboard currently filled with numbers, arithmetic operations, and various parentheses).
- Custom macros or substitutions (support needed in main codebase as well). So users can, for instance, set a substitution `c to f` expanding into `celsius to fahrenheit`.

Please feel free to contribute code, ideas, etc! This app is open-source for a reason.

**Comment by licaon-kter** [comment]
- Dark themes: Material and Black (AMOLED)
- ENTER key customisation (you now have 2 with the same function?)
- Thousands separator (dot, comma, space, none)
- Decimal simbol (dot, comma)

**Comment by stpr-dev** [comment]
Also see #7 , #3

**Comment by icasdri** [comment]
A very basic Settings activity has been implemented in ca21fec.
