### ISSUE TITLE
Logo in F-Droid is broken

### ISSUE THREAD

**Issue by stpr-dev** [icasdri/Mather#11]
I do not think Mather has a logo yet, at least according to F-Droid.  We definitely need a good logo for it!

**Comment by icasdri** [comment]
Mather certainly has a logo (which you should see once the app is installed). However, F-Droid's build servers are not picking it up. Thus, it does not show up in F-Droid. The logo is in [app_icon.xml](https://github.com/icasdri/Mather/blob/master/app/src/main/res/drawable/app_icon.xml) as an Android drawable.

**Comment by stpr-dev** [comment]
@icasdri 

Ah yes, that explains it. Hopefully they will fix it soon.

**Comment by icasdri** [comment]
This appears to have been fixed with the recent F-Droid overhaul: https://f-droid.org/packages/org.icasdri.mather/
