### ISSUE TITLE
Empty calculation gives strange results

### ISSUE THREAD

**Issue by vanitasvitae** [icasdri/Mather#5]
Hi!
When I calculate some terms and then press the results button multiple times without entering a new function, Mather gives me different results. How are those results to be interpreted?

Nice app BTW :)

**Comment by icasdri** [comment]
Hmmm... interesting issue. This could potentially be due to the underlying javascript library not keeping up, and evaluating some previous expressions. I might just disallow eval-ing on an empty input.
